import Foundation
import Model

/// Plans an old-browser cleanup from the imported credentials: which saved
/// logins (in browsers you've migrated away from) can be removed, and the
/// `rekey-cleanup` script to do it. Pure logic — the app never deletes anything.
///
/// Granularity is per **(old browser, site)** because that matches the tool's
/// capability (Firefox usernames are encrypted, so deletion is by host), and it
/// matches the intent: "remove this site's logins from the browser I left."
/// Safety is still judged per-username: a site is "safe to clear" only if *every*
/// username it has in the old browser also exists in the browser you're keeping.
enum CleanupPlanner {
    struct Candidate: Identifiable, Hashable {
        let browser: BrowserSource
        let domain: String
        /// Distinct usernames this site has in the old browser (for display).
        let usernames: [String]
        /// Usernames here that are NOT also saved in the kept browser — deleting
        /// the site removes these, and they'd be lost.
        let soleCopyUsernames: [String]

        /// True when nothing would be lost (every username is also in `keep`).
        var fullySafe: Bool { soleCopyUsernames.isEmpty }
        var id: String { "\(browser.rawValue)|\(domain)" }
    }

    /// Distinct source browsers among imported credentials (for the "keep" picker).
    static func importedBrowsers(in creds: [ImportedCredential]) -> [BrowserSource] {
        var seen: [BrowserSource] = []
        for c in creds where !seen.contains(c.source) { seen.append(c.source) }
        return seen.sorted { $0.displayName < $1.displayName }
    }

    /// Cleanup candidates: every (old browser, site) where the old browser is a
    /// cleanup-supported browser other than `keep`.
    static func candidates(from creds: [ImportedCredential], keep: BrowserSource) -> [Candidate] {
        let keepKeys = Set(
            creds.filter { $0.source == keep }.map { "\($0.registrableDomain)|\($0.username)" }
        )
        let old = creds.filter { $0.source != keep && $0.source.cleanupSupported }
        let grouped = Dictionary(grouping: old) { "\($0.source.rawValue)|\($0.registrableDomain)" }

        var out: [Candidate] = []
        for (_, group) in grouped {
            guard let first = group.first else { continue }
            let usernames = Array(Set(group.map(\.username))).sorted()
            let sole = usernames.filter { !keepKeys.contains("\(first.registrableDomain)|\($0)") }
            out.append(Candidate(
                browser: first.source,
                domain: first.registrableDomain,
                usernames: usernames,
                soleCopyUsernames: sole
            ))
        }
        return out.sorted { ($0.browser.displayName, $0.domain) < ($1.browser.displayName, $1.domain) }
    }

    /// Site-level `rekey-cleanup` command for a candidate, or nil if unsupported.
    static func command(for candidate: Candidate, confirm: Bool) -> String? {
        guard let browser = candidate.browser.cleanupCLIName else { return nil }
        var cmd = "rekey-cleanup delete --browser \(browser) --site \(candidate.domain)"
        if confirm { cmd += " --confirm" }
        return cmd
    }

    /// Shared script preamble: shebang, the quit-browser / backup note, the
    /// optional PREVIEW banner, and `set -e`.
    private static func header(_ purpose: String, confirm: Bool) -> [String] {
        var lines = [
            "#!/bin/sh",
            "# Generated by Rekey — \(purpose)",
            "# Quit the listed browser(s) first: rekey-cleanup refuses to run while a browser is",
            "# open, and backs up its store before deleting.",
            "# Requires rekey-cleanup on your PATH (or use: swift run rekey-cleanup, from the Rekey dir).",
        ]
        if !confirm {
            lines.append("# PREVIEW ONLY (no --confirm): this just shows what WOULD be deleted.")
        }
        lines.append("set -e")
        lines.append("")
        return lines
    }

    /// Build the runnable script for the selected candidates.
    static func script(for selected: [Candidate], confirm: Bool) -> String {
        guard !selected.isEmpty else { return "" }
        var lines = header("remove stale logins from browsers you've migrated away from.", confirm: confirm)

        let byBrowser = Dictionary(grouping: selected, by: \.browser)
        for browser in byBrowser.keys.sorted(by: { $0.displayName < $1.displayName }) {
            lines.append("# --- \(browser.displayName) ---")
            for candidate in byBrowser[browser]!.sorted(by: { $0.domain < $1.domain }) {
                if let cmd = command(for: candidate, confirm: confirm) {
                    lines.append(cmd)
                }
            }
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    /// Wrap ready-made dry-run `rekey-cleanup delete` commands — one per login the
    /// user has re-keyed, across all browsers — into a single runnable script.
    /// Commands must be unique and carry no `--confirm`; this adds the header and,
    /// when requested, `--confirm` to each line.
    static func script(commands: [String], confirm: Bool) -> String {
        guard !commands.isEmpty else { return "" }
        var lines = header("remove the old saved logins for the accounts you've re-keyed.", confirm: confirm)
        for cmd in commands {
            lines.append(confirm ? cmd + " --confirm" : cmd)
        }
        return lines.joined(separator: "\n")
    }
}
